config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "cars#index"

  resources :cars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :car_listings
  has_many :dealerships, through: :car_listings
  has_one_attached :photo, dependent: :destroy
  
  enum condition: HashWithIndifferentAccess.new(brand_new: "brand_new", used: "used")

  def current_price
    price = original_price
    months_passed = get_months_since_release

    months_passed.times do
      price = price * 0.98
    end

    price
  end

  def price
    current_price.round(2)
  end

  private
  
  def get_months_since_release
    today = DateTime.current
    months_since_release = (today.year * 12 + today.month) - (release_date.year * 12 + release_date.month)

    if today.day < release_date.day
      months_since_release = months_since_release - 1
    end

    months_since_release
  end
end

app/models/car_listing.rb
class CarListing < ApplicationRecord
  belongs_to :car
  belongs_to :dealership
end

app/models/dealership.rb
class Dealership < ApplicationRecord
  has_many :car_listings
  has_many :cars, through: :car_listing
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: HashWithIndifferentAccess.new(user: "user", admin: "admin")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new(release_date: DateTime.current)
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      flash[:success] = "Car created successfully"
      
      redirect_to cars_path
    else
      flash.now[:error] = "Error creating cart"

      render :new
    end
  end

  def destroy
    @car.destroy

    flash[:success] = "Car deleted successfully"

    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:name, :release_date, :original_price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/index.html.erb
<% if current_user.admin? %>
  <%= link_to "Crear carro", new_car_path %>
<% end %>
<% @cars.each do |car| %>
  <div>
    <h3><%= car.name.titleize %> <%= car.release_date.year %><small> | <%= link_to("Delete", car_path(car), method: "DELETE") if current_user.admin? %></small></h3>
    <p><strong>Price: </strong> <%= number_to_currency(car.price) %></p>
    <p><strong>Available at: </strong/> <%= car.car_listings.map(&:dealership).uniq.map(&:name).join(", ") %></p>
  </div>
<% end %>

app/views/cars/new.html.erb
<%= form_with(model: @car) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name, required: true %>

  <%= form.label :release_date %>
  <%= form.date_field :release_date, required: true %>

  <%= form.label :original_price %>
  <%= form.number_field :original_price, required: true %>

  <%= form.label :photo %>
  <%= form.file_field :photo %>

  <%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Semiused</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>